export const FETCH_MEDICATIONS = "FETCH_MEDICATIONS";
export const FETCH_USERDATA = "FETCH_USERDATA";

export const FETCH_NOTITFICATIONS = "FETCH_NOTIFICATIONS";

export const FETCH_MEDICATIONS_ACTION = {
  type: FETCH_MEDICATIONS,
};

export const UPDATE_MEDICATIONS = {
  medications: [],
};

export const MEDICATION_ACTION_TYPES = {
  FETCH_MEDICATIONS,
};
export const USERDATA_ACTION_TYPES = {
  FETCH_USERDATA,
};
